//! Generate abstract Magnolia signatures from WIT worlds.
//!
//! This first implementation intentionally stops before canonical-ABI or
//! WebAssembly glue. WIT operations are emitted as Magnolia procedures because
//! WIT does not promise that a function is pure. A WIT result therefore becomes
//! an `out` procedure parameter.

use std::collections::BTreeSet;
use std::fmt::Write;

use anyhow::{Result, bail};
use heck::{ToSnakeCase, ToUpperCamelCase};
use wit_bindgen_core::{Files, Source, WorldGenerator, uwriteln, wit_parser::*};

#[derive(Default, Debug, Clone)]
#[cfg_attr(feature = "clap", derive(clap::Args))]
pub struct Opts {}

impl Opts {
    pub fn build(&self) -> Box<dyn WorldGenerator> {
        Box::new(Magnolia::default())
    }
}

#[derive(Default)]
struct Magnolia {
    package: String,
    world: String,
    types: BTreeSet<LeafType>,
    sections: Vec<Section>,
}

struct Section {
    signature: String,
    description: String,
    operations: Vec<Operation>,
}

struct Operation {
    name: String,
    params: Vec<(String, LeafType, bool)>,
    result: Option<LeafType>,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
enum LeafType {
    Bool,
    U8,
    S8,
    U16,
    S16,
    U32,
    S32,
    U64,
    S64,
    F32,
    F64,
    Char,
    String,
    ErrorContext,
}

impl LeafType {
    fn magnolia_name(self) -> &'static str {
        match self {
            Self::Bool => "WitBool",
            Self::U8 => "WitU8",
            Self::S8 => "WitS8",
            Self::U16 => "WitU16",
            Self::S16 => "WitS16",
            Self::U32 => "WitU32",
            Self::S32 => "WitS32",
            Self::U64 => "WitU64",
            Self::S64 => "WitS64",
            Self::F32 => "WitF32",
            Self::F64 => "WitF64",
            Self::Char => "WitChar",
            Self::String => "WitString",
            Self::ErrorContext => "WitErrorContext",
        }
    }
}

impl Magnolia {
    fn collect_operation(&mut self, resolve: &Resolve, func: &Function) -> Result<Operation> {
        let mut params = Vec::new();
        for param in &func.params {
            let ty = leaf_type(resolve, &param.ty)?;
            self.types.insert(ty);
            params.push((param.name.to_snake_case(), ty, param.is_out));
        }

        let result = func
            .result
            .as_ref()
            .map(|ty| leaf_type(resolve, ty))
            .transpose()?;
        if let Some(ty) = result {
            self.types.insert(ty);
        }

        Ok(Operation {
            name: func.name.to_snake_case(),
            params,
            result,
        })
    }

    fn collect_section<'a>(
        &mut self,
        resolve: &Resolve,
        signature: String,
        description: String,
        functions: impl IntoIterator<Item = &'a Function>,
    ) -> Result<()> {
        let operations = functions
            .into_iter()
            .map(|func| self.collect_operation(resolve, func))
            .collect::<Result<Vec<_>>>()?;

        if !operations.is_empty() {
            self.sections.push(Section {
                signature,
                description,
                operations,
            });
        }
        Ok(())
    }

    fn interface_signature(&self, interface: &str, direction: &str) -> String {
        format!(
            "{}{}{}",
            self.world,
            interface.to_upper_camel_case(),
            direction
        )
    }

    fn emit(&self) -> Source {
        let mut src = Source::default();
        uwriteln!(src, "package {};\n", self.package);
        uwriteln!(src, "// Generated by wit-bindgen-magnolia.");
        uwriteln!(
            src,
            "// Types are abstract; their representation is supplied by the target backend.\n"
        );

        if !self.types.is_empty() {
            uwriteln!(src, "signature {}Types = {{", self.world);
            for ty in &self.types {
                uwriteln!(src, "type {};", ty.magnolia_name());
            }
            uwriteln!(src, "}}\n");
        }

        for section in &self.sections {
            uwriteln!(src, "// {}", section.description);
            uwriteln!(src, "signature {} = {{", section.signature);
            if !self.types.is_empty() {
                uwriteln!(src, "use {}Types;", self.world);
            }
            for operation in &section.operations {
                emit_operation(&mut src, operation);
            }
            uwriteln!(src, "}}\n");
        }

        src
    }
}

impl WorldGenerator for Magnolia {
    fn preprocess(&mut self, resolve: &Resolve, world: WorldId) -> Result<()> {
        self.package = resolve.worlds[world].name.to_snake_case();
        self.world = resolve.worlds[world].name.to_upper_camel_case();
        Ok(())
    }

    fn import_interface(
        &mut self,
        resolve: &Resolve,
        name: &WorldKey,
        interface: InterfaceId,
        _files: &mut Files,
    ) -> Result<()> {
        let name = resolve.name_world_key(name);
        self.collect_section(
            resolve,
            self.interface_signature(&name, "Imports"),
            format!("WIT import interface `{name}`."),
            resolve.interfaces[interface].functions.values(),
        )
    }

    fn export_interface(
        &mut self,
        resolve: &Resolve,
        name: &WorldKey,
        interface: InterfaceId,
        _files: &mut Files,
    ) -> Result<()> {
        let name = resolve.name_world_key(name);
        self.collect_section(
            resolve,
            self.interface_signature(&name, "Exports"),
            format!("WIT export interface `{name}`."),
            resolve.interfaces[interface].functions.values(),
        )
    }

    fn import_funcs(
        &mut self,
        resolve: &Resolve,
        _world: WorldId,
        funcs: &[(&str, &Function)],
        _files: &mut Files,
    ) -> Result<()> {
        self.collect_section(
            resolve,
            format!("{}Imports", self.world),
            "WIT world imports.".to_string(),
            funcs.iter().map(|(_, func)| *func),
        )
    }

    fn export_funcs(
        &mut self,
        resolve: &Resolve,
        _world: WorldId,
        funcs: &[(&str, &Function)],
        _files: &mut Files,
    ) -> Result<()> {
        self.collect_section(
            resolve,
            format!("{}Exports", self.world),
            "WIT world exports.".to_string(),
            funcs.iter().map(|(_, func)| *func),
        )
    }

    fn import_types(
        &mut self,
        _resolve: &Resolve,
        _world: WorldId,
        types: &[(&str, TypeId)],
        _files: &mut Files,
    ) -> Result<()> {
        if let Some((name, _)) = types.first() {
            bail!(
                "world-level imported type `{name}` is not supported by the initial scalar-only Magnolia generator"
            );
        }
        Ok(())
    }

    fn finish(&mut self, resolve: &Resolve, world: WorldId, files: &mut Files) -> Result<()> {
        let filename = format!("{}.mg", resolve.worlds[world].name.to_snake_case());
        files.push(&filename, self.emit().as_bytes());
        Ok(())
    }
}

fn leaf_type(resolve: &Resolve, ty: &Type) -> Result<LeafType> {
    Ok(match ty {
        Type::Bool => LeafType::Bool,
        Type::U8 => LeafType::U8,
        Type::S8 => LeafType::S8,
        Type::U16 => LeafType::U16,
        Type::S16 => LeafType::S16,
        Type::U32 => LeafType::U32,
        Type::S32 => LeafType::S32,
        Type::U64 => LeafType::U64,
        Type::S64 => LeafType::S64,
        Type::F32 => LeafType::F32,
        Type::F64 => LeafType::F64,
        Type::Char => LeafType::Char,
        Type::String => LeafType::String,
        Type::ErrorContext => LeafType::ErrorContext,
        Type::Id(id) => match &resolve.types[*id].kind {
            TypeDefKind::Type(inner) => return leaf_type(resolve, inner),
            kind => {
                let name = resolve.types[*id].name.as_deref().unwrap_or("<anonymous>");
                bail!(
                    "WIT type `{name}` ({kind:?}) is not supported by the initial scalar-only Magnolia generator"
                )
            }
        },
    })
}

fn emit_operation(src: &mut Source, operation: &Operation) {
    let mut parameters = operation
        .params
        .iter()
        .map(|(name, ty, is_out)| {
            let mode = if *is_out { "out" } else { "obs" };
            format!("{mode} {name}: {}", ty.magnolia_name())
        })
        .collect::<Vec<_>>();

    if let Some(ty) = operation.result {
        let mut result_name = "result".to_string();
        while operation
            .params
            .iter()
            .any(|(parameter, _, _)| parameter == &result_name)
        {
            result_name.push('_');
        }
        parameters.push(format!("out {result_name}: {}", ty.magnolia_name()));
    }

    uwriteln!(
        src,
        "procedure {}({});",
        operation.name,
        parameters.join(", ")
    );
}
