[package]
name = "wit-bindgen-magnolia"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
description = """
Magnolia generator for WIT and the component model, typically used
through the `wit-bindgen-cli` crate.
"""

[lints]
workspace = true

[lib]
doctest = false
test = false

[features]
clap = ['dep:clap', 'wit-bindgen-core/clap']

[dependencies]
anyhow = { workspace = true }
heck = { workspace = true }
clap = { workspace = true, optional = true }
wit-bindgen-core = { workspace = true }
